### ISSUE TITLE
[BUG] Commands are not available durin update even if it's already installed

### ISSUE THREAD

**Issue by mrjxtr** [mylinuxforwork/dotfiles#484]
**Describe the bug**

When I try to use `ml4w-hyprland-setup` to reinstall my dotfiles and hopefully get the sidebar and clock or calendar to work from that AGS issue, it gave me this.

It mentions commands that are "not available" when it already installed.

```bash
:: hyprland is already installed.
:: hyprpaper is already installed.
:: hyprlock is already installed.
:: hypridle is already installed.
:: noto-fonts is already installed.
:: xdg-desktop-portal-hyprland is already installed.
:: libnotify is already installed.
:: dunst is already installed.
:: kitty is already installed.
:: qt5-wayland is already installed.
:: qt6-wayland is already installed.
:: fastfetch is already installed.
:: eza is already installed.
:: python-pip is already installed.
:: python-gobject is already installed.
:: python-screeninfo is already installed.
:: tumbler is already installed.
:: brightnessctl is already installed.
:: nm-connection-editor is already installed.
:: network-manager-applet is already installed.
:: gtk4 is already installed.
:: libadwaita is already installed.
:: fuse2 is already installed.
:: imagemagick is already installed.
:: jq is already installed.
:: xclip is already installed.
:: firefox is already installed.
:: kitty is already installed.
:: neovim is already installed.
:: htop is already installed.
:: nautilus is already installed.
:: nautilus-open-any-terminal is already installed.
:: python-pywal is already installed.
:: pinta is already installed.
:: blueman is already installed.
:: grim is already installed.
:: slurp is already installed.
:: cliphist is already installed.
:: nwg-look is already installed.
:: qt6ct is already installed.
:: waybar is already installed.
:: rofi-wayland is already installed.
:: polkit-gnome is already installed.
:: zsh is already installed.
:: zsh-completions is already installed.
:: fzf is already installed.
:: pavucontrol is already installed.
:: papirus-icon-theme is already installed.
:: breeze is already installed.
:: gvfs is already installed.
:: wlogout is already installed.
:: hyprshade is already installed.
:: waypaper is already installed.
:: grimblast-git is already installed.
:: bibata-cursor-theme-bin is already installed.
:: pacseek is already installed.
:: otf-font-awesome is already installed.
:: ttf-fira-sans is already installed.
:: ttf-fira-code is already installed.
:: ttf-firacode-nerd is already installed.
:: aylurs-gtk-shell is already installed.

   ___  _                         _   
  / _ \(_)__ ____ ____  ___  ___ (_)__
 / // / / _ `/ _ `/ _ \/ _ \(_-</ (_-<
/____/_/\_,_/\_, /_//_/\___/___/_/___/
            /___/                     

:: ERROR - Some required commands are not available:
dunst waybar hyprpaper hyprlock hypridle hyprshade wal gum wlogout ags magick waypaper
```

**To Reproduce**
1. `ml4w-hyprland-setup`

**Expected behavior**
I can proceed with the re-installation of dotfiles without this error

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by mrjxtr** [comment]
Update, I run the built in updater and found out there was a new version of ml4w-hyprland on the aur, did an update and did `ml4w-hyprland-setup` again and the error is not there anymore... but hopefully the setup fixes the sidebar and the calendar

**Comment by mylinuxforwork** [comment]
@mrjxtr Thanks for testing. The sidebar issue is fixed as well. Please make sure that ags 2.0.1 is installed on your system.

**Comment by mrjxtr** [comment]
> @mrjxtr Thanks for testing. The sidebar issue is fixed as well. Please make sure that ags 2.0.1 is installed on your system.

Yes I do have aylurs-gtk-shell-2.0.1-3 installed but it still does not work.

**Comment by mylinuxforwork** [comment]
@mrjxtr Can you please try to update to 2.9.7.0RC1 and try again? https://github.com/mylinuxforwork/dotfiles/wiki/Installation

**Comment by mrjxtr** [comment]
> @mrjxtr Can you please try to update to 2.9.7.0RC1 and try again? https://github.com/mylinuxforwork/dotfiles/wiki/Installation

Done... still no sidebar.

what I did
- `yay -Syu`
- `ml4w-hyprland-setup`
